---
name: youtube-integration
---
Dynamic\YouTubeIntegration\Page\VideosPage:
  extensions:
    - Dynamic\YouTubeIntegration\Extension\YouTubeVideoManager
Dynamic\YouTubeIntegration\Page\VideoPlaylistsPage:
  extensions:
    - Dynamic\YouTubeIntegration\Extension\CustomYouTubeVideoPlaylistManager
Dynamic\YouTubeIntegration\Model\YouTubeVideoPlaylist:
  extensions:
    - Dynamic\YouTubeIntegration\Extension\YouTubeVideoManager
