---
name: youtube-integration
---
YouTubeIntegrationVideosPage:
  extensions:
    - YouTubeVideoManager
YouTubeIntegrationPlaylistsPage:
  extensions:
    - CustomYouTubeVideoPlaylistManager
YouTubeVideoPlaylist:
  extensions:
    - YouTubeVideoManager