---
name: youtube-integration
---
Dynamic\YouTubeIntegration\Page\YouTubeIntegrationVideosPage:
  extensions:
    - Dynamic\YouTubeIntegration\DataExtension\YouTubeVideoManager
Dynamic\YouTubeIntegration\Page\YouTubeIntegrationPlaylistsPage:
  extensions:
    - Dynamic\YouTubeIntegration\DataExtension\CustomYouTubeVideoPlaylistManager
Dynamic\YouTubeIntegration\DataObject\YouTubeVideoPlaylist:
  extensions:
    - Dynamic\YouTubeIntegration\DataExtension\YouTubeVideoManager